#!/usr/bin/env python

Import('env')
Import('env_modules')

env_physicstools = env_modules.Clone()

# Module source files
source_dirs = [
	"./",
]
env_physicstools.Prepend(CPPPATH=source_dirs)
sources = [Glob(d + "*.cpp") for d in source_dirs]

env_physicstools.add_source_files(env.modules_sources, sources)
